### ISSUE TITLE
Example for LinearMapAO?

### ISSUE THREAD

**Issue by jlchan** [JeffFessler/LinearMapsAA.jl#22]
I was trying to explore functionality mentioned in this comment https://github.com/Jutho/LinearMaps.jl/issues/44#issuecomment-651152965, but couldn't figure out how to create a `LinearMapAO` (or `LinearMapAX`). Is there an example available somewhere?

**Comment by JeffFessler** [comment]
Oh, the example given in the README right here is one such example:
https://github.com/JeffFessler/LinearMapsAA.jl#operator-support
I added another example to the README in case that helps.

For a real example see:
https://github.com/JeffFessler/MIRT.jl/blob/efb5ec8c8875bf8bbb74932550825e5bf07b5497/src/regularize/Aodwt.jl#L52

You still use the method `LinearMapAA` but the type returned is `LinearMapAO`.
