### ISSUE TITLE
return GPU arrays

### ISSUE THREAD

**Issue by ZongyuLi-umich** [JeffFessler/LinearMapsAA.jl#47]
When running the following block of code
```julia
using LinearMapsAA
nx = 8
ny = 8
nz = 6
idim = (nx,ny,nz)
odim = (nx,ny,nz)
T = Float32
A = LinearMapAA(x -> 2 * x, y -> 2 * y, (prod(odim), prod(idim)); T, odim, idim)
A * CuArray(ones(T, nx, ny, nz))
```
it returns an array of type `Array{Float32, 3}` not `CuArray{Float32, 3}`.
So I am thinking that we should make the type of output and input to be consistent.
I am using Julia v1.6.3 on Ubuntu 20.04 and `LinearMapsAA`@v0.10.0.

**Comment by JeffFessler** [comment]
Agreed.  Can you try it with `LinearMap`?

**Comment by ZongyuLi-umich** [comment]
Never mind, sorry. I solved this issue by simply restarting Julia.
